const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{credentials:'include',...options});const type=r.headers.get('content-type')||'';const body=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(body.error||body);return body}
function message(el,text,bad=false){el.innerHTML=text?`<div class="notice ${bad?'error':''}">${esc(text)}</div>`:''}
async function boot(){try{await api('/api/auth/me');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#logout').classList.remove('hidden');await contracts()}catch{}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});location.reload()}catch(x){message($('#loginMessage'),x.message,true)}};
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));['contracts','create','audit'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==b.dataset.view));if(b.dataset.view==='contracts')await contracts();if(b.dataset.view==='audit')await audit()});
$('#createForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const email=String(form.get('signerEmail')||'').trim();const pdf=form.get('pdf');if(!String(form.get('title')||'').trim()||!String(form.get('companyName')||'').trim()||!String(form.get('signerName')||'').trim()){message($('#createMessage'),'すべての契約情報を入力してください。',true);return}if(!/^\S+@\S+\.\S+$/.test(email)){message($('#createMessage'),'有効な署名者メールアドレスを入力してください。',true);return}if(!(pdf instanceof File)||!pdf.name){message($('#createMessage'),'契約書PDFを選択してください。',true);return}message($('#createMessage'),'アップロード中…');try{await api('/api/contracts',{method:'POST',body:form});e.target.reset();message($('#createMessage'),'契約を作成しました。');}catch(x){message($('#createMessage'),x.message,true)}};
async function contracts(){const rows=await api('/api/contracts');$('#contractRows').innerHTML=rows.map(c=>`<tr><td>${esc(c.title)}<br><span class="hash">${esc(c.id)}</span></td><td>${esc(c.signer_name)}<br>${esc(c.signer_email)}</td><td class="status ${esc(c.status)}">${esc(c.status)}</td><td>${new Date(c.created_at).toLocaleString('ja-JP')}</td><td>${c.status==='draft'?`<button data-send="${c.id}">署名URL発行</button>`:''} ${['draft','sent'].includes(c.status)?`<button class="danger" data-void="${c.id}">破棄</button>`:''} <a class="button secondary" href="/api/contracts/${c.id}/pdf" target="_blank">PDF</a>${c.status==='signed'?` <a class="button" href="/api/contracts/${c.id}/signed-pdf" target="_blank">署名済</a> <a class="button secondary" href="/api/contracts/${c.id}/certificate" target="_blank">証明書</a>`:''}</td></tr>`).join('');
document.querySelectorAll('[data-send]').forEach(b=>b.onclick=async()=>{try{const x=await api(`/api/contracts/${b.dataset.send}/send`,{method:'POST'});message($('#contractMessage'),`署名URL（この画面で一度だけ表示）\n${x.signingUrl}\n有効期限: ${x.expiresAt}`);await contracts()}catch(x){message($('#contractMessage'),x.message,true)}});document.querySelectorAll('[data-void]').forEach(b=>b.onclick=async()=>{if(confirm('この契約を破棄しますか？')){await api(`/api/contracts/${b.dataset.void}/void`,{method:'POST'});await contracts()}})}
async function audit(){const rows=await api('/api/audit');$('#auditRows').innerHTML=rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('ja-JP')}</td><td>${esc(x.event_type)}<br><span class="hash">${esc(x.contract_id)}</span></td><td>${esc(x.actor_type)}<br>${esc(x.actor_reference)}</td><td class="hash">${esc(x.previous_hash)}<br>↓<br>${esc(x.record_hash)}</td></tr>`).join('')}
boot();
